# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

env:
    global:
        - ARTIFACTS_DIR=build/travis-artifacts
        - DIST=xenial
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

install: beaver install

# (Ab)use Travis cache to pass artifacts between stages.
# As long as the environment variables of different stages match, travis will
# pull the same "cache", so we can use this to actually pass artifacts between
# stages.
cache:
    directories:
        - $ARTIFACTS_DIR

jobs:
    include:
        # env: before_install: and install: are inherited and we don't need
        # to override them.
        - stage: Test
          script:
              - beaver make F=cdgc.release all test pkg
              # If this is a tag, save the packages in the cache directory so
              # it's accessible in the Upload Package stage
              - if test -n "$TRAVIS_TAG"; then
                    cp -v build/last/pkg/*.deb "build/$ARTIFACTS_DIR/";
                fi
        - stage: Upload Package
          # We need to include the exclusion of D2 tags because this "if"
          # replaces the global one
          if: tag IS present
          script:
              - beaver bintray upload -d sociomantic-tsunami/dlang/tangort
                "$ARTIFACTS_DIR"/*.deb
